// apps/driver/src/components/Sparkline.tsx
import Svg, { Circle, Polyline } from 'react-native-svg';
import { roleColors } from '@/theme/colors';
import { useTheme } from '@/theme/ThemeProvider';

// Tiny trend line for stat tiles — the shape of the last N periods at a glance. Stretches to its
// container width; the end-point dot marks "now".
export function Sparkline({ data, height = 22 }: { data: number[]; height?: number }) {
  const { themeKey } = useTheme();
  const rc = roleColors[themeKey];

  if (data.length < 2) return null;
  const W = 100;
  const P = 3;
  const min = Math.min(...data);
  const max = Math.max(...data);
  const span = max - min || 1;

  const pts = data.map((v, i) => ({
    x: P + (i * (W - 2 * P)) / (data.length - 1),
    y: P + (1 - (v - min) / span) * (height - 2 * P),
  }));
  const last = pts.at(-1);
  if (!last) return null;

  return (
    <Svg width="100%" height={height} viewBox={`0 0 ${W} ${height}`} preserveAspectRatio="none">
      <Polyline
        points={pts.map((p) => `${p.x},${p.y}`).join(' ')}
        fill="none"
        stroke={rc.brand}
        strokeWidth={1.75}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <Circle cx={last.x} cy={last.y} r={2.4} fill={rc.brand} />
    </Svg>
  );
}

// apps/web/src/components/SparkLine.vue
<script setup lang="ts">
import { computed } from "vue";

/**
 * Dependency-free SVG sparkline for stat tiles. Null points render as honest gaps
 * (the polyline splits), matching how the full-size trend charts treat missing days.
 */
const props = defineProps<{
  points: (number | null)[];
  color: string;
}>();

const W = 120;
const H = 36;
const PAD = 3;

const segments = computed<string[]>(() => {
  const pts = props.points;
  const vals = pts.filter((p): p is number => p != null);
  if (vals.length < 2) return [];
  const min = Math.min(...vals);
  const max = Math.max(...vals);
  const span = max - min || 1;
  const step = pts.length > 1 ? (W - PAD * 2) / (pts.length - 1) : 0;

  const segs: string[] = [];
  let current: string[] = [];
  pts.forEach((p, i) => {
    if (p == null) {
      if (current.length > 1) segs.push(current.join(" "));
      current = [];
      return;
    }
    const x = PAD + i * step;
    const y = PAD + (1 - (p - min) / span) * (H - PAD * 2);
    current.push(`${x.toFixed(1)},${y.toFixed(1)}`);
  });
  if (current.length > 1) segs.push(current.join(" "));
  return segs;
});

const endDot = computed<{ x: number; y: number } | null>(() => {
  const last = segments.value.at(-1)?.split(" ").at(-1);
  if (!last) return null;
  const [x, y] = last.split(",").map(Number);
  return { x: x!, y: y! };
});
</script>

<template>
  <svg
    v-if="segments.length"
    :viewBox="`0 0 ${W} ${H}`"
    class="h-9 w-full"
    preserveAspectRatio="none"
    aria-hidden="true"
  >
    <polyline
      v-for="(seg, i) in segments"
      :key="i"
      :points="seg"
      fill="none"
      :stroke="color"
      stroke-width="1.75"
      stroke-linecap="round"
      stroke-linejoin="round"
      vector-effect="non-scaling-stroke"
    />
    <circle v-if="endDot" :cx="endDot.x" :cy="endDot.y" r="2.5" :fill="color" stroke="white" stroke-width="1.5" />
  </svg>
</template>
